# Generated by Django 4.1.4 on 2022-12-14 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manga_name', models.CharField(blank=True, max_length=255)),
                ('manga_description', models.TextField()),
                ('manga_genre', models.CharField(blank=True, max_length=255)),
                ('manga_rating', models.IntegerField()),
                ('manga_purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=255)),
                ('book_description', models.TextField()),
                ('book_author', models.CharField(blank=True, max_length=255)),
                ('book_genre', models.CharField(blank=True, max_length=255)),
                ('book_rating', models.IntegerField()),
                ('book_purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
